### ISSUE TITLE
Inheritance Again

### ISSUE THREAD

**Issue by jsr5194** [Talos-Martin/LearnTheHardWay#11]
https://github.com/Talos-Martin/LearnTheHardWay/blob/c2dfb6b7230488d573a2c93afc5ca345fd1ff15e/Python3/exercise43/ex43.py#L107

This goes back to my answer in https://github.com/Talos-Martin/LearnTheHardWay/issues/10. In this case you would not be able to inherit functions from the `Scene` class

**Comment by Talos-Martin** [comment]
Yep, got it.
