### ISSUE TITLE
Comma on last line

### ISSUE THREAD

**Issue by jsr5194** [Talos-Martin/LearnTheHardWay#12]
https://github.com/Talos-Martin/LearnTheHardWay/blob/c2dfb6b7230488d573a2c93afc5ca345fd1ff15e/Python3/exercise43/ex43.py#L271

It is not technically required, though I think here he includes it for line consistency. 

The main place I can think of where this is required is when defining a tuple with only one element, like so `('abc',)`
ref: https://docs.python.org/3/reference/datamodel.html#index-20

**Comment by Talos-Martin** [comment]
Got it
