### ISSUE TITLE
Pythonic Opening

### ISSUE THREAD

**Issue by Knight-Ops** [Talos-Martin/LearnTheHardWay#2]
https://github.com/Talos-Martin/LearnTheHardWay/blob/669b82d6b622e82392b0baac91c81f867ef4297a/Python3/exercise17/ex17.py#L13

Zed doesn't cover the more common (and accepted) way of opening files. Usually in python you will see this idiom

```
with open(from_file, "r") as f:
    inbuf = f.read()
```

While this isn't 1 line, it is significantly easier to read, and Python closes the file for you automatically when it goes out of scope.

**Comment by Talos-Martin** [comment]
He wanted a one-liner, so I came up with that. But it's just ugly and I wouldnt use it in real code. 
I haven't seen your way of opening a file, but that's much better style.
