### ISSUE TITLE
Python open() encoding

### ISSUE THREAD

**Issue by jsr5194** [Talos-Martin/LearnTheHardWay#3]
https://github.com/Talos-Martin/LearnTheHardWay/blob/5e0f0053a8644479a945c5386c3cc85eb4ed7b4a/Python3/exercise23/ex23.py#L35

That is a great question. Did you figure out why he is doing this here? And more importantly, did you notice the effects that it will have if you're trying to read a binary file?

**Comment by Talos-Martin** [comment]
I tried without the parameter encoding(just open()), with utf-8 and utf-16. UTF-16 fails right away. The other two seem to produce the same result!?

**Comment by jsr5194** [comment]
Closing since we talked in a call about this
