### ISSUE TITLE
print end parameter

### ISSUE THREAD

**Issue by jsr5194** [Talos-Martin/LearnTheHardWay#4]
https://github.com/Talos-Martin/LearnTheHardWay/blob/5e0f0053a8644479a945c5386c3cc85eb4ed7b4a/Python3/exercise20/ex20.py#L12

python3's print function automatically appends a newline to the end of whatever content is given to print. By specifying the 'end' parameter you can override that ending to be whatever you want. As for your question of why you have to specify the 'end' keyword itself, this is just due to how python handles optional parameters. If it was a required parameter you would not need to do this

**Comment by Talos-Martin** [comment]
Got it. End is also not just some arbitrary variable name, like I thought, but a specific modifier/parameter. Using test='' doesn't work. Just tested.
