### ISSUE TITLE
Range function

### ISSUE THREAD

**Issue by jsr5194** [Talos-Martin/LearnTheHardWay#5]
https://github.com/Talos-Martin/LearnTheHardWay/blob/8d66876f1fba361202a432ade475cb52673b29c9/Python3/exercise33/ex33.py#L16

Personally I'm a fan of being explicit like you have done here, but I wanted to point out that python's range function assumes that the starting point is 0 if only one value is given. 
For example
`for i in range(0,max):`
does effectively the same thing as
`for i in range(max):`

**Comment by Talos-Martin** [comment]
That's smart and makes perfect sense. Thanks! I had no idea.
