### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by jsr5194** [Talos-Martin/LearnTheHardWay#6]
https://github.com/Talos-Martin/LearnTheHardWay/blob/8d66876f1fba361202a432ade475cb52673b29c9/Python3/exercise35/ex35.py#L8

He doesn't address it in the book, but what would happen here if the input was something like `abc0`? Would the `int()` cast still work?

**Comment by Talos-Martin** [comment]
It would break. I had that problem in ex36 and used a try/catch to gracefully handle the situation.
