### ISSUE TITLE
Key-Value pair

### ISSUE THREAD

**Issue by jsr5194** [Talos-Martin/LearnTheHardWay#7]
https://github.com/Talos-Martin/LearnTheHardWay/blob/c2dfb6b7230488d573a2c93afc5ca345fd1ff15e/Python3/exercise39/ex39.py#L50

Correct, dicts in python are intended to be used with just the key for lookup. With that said, it is possible to find a key from its value, but it will be a bit more manual approach using something like `list.items()`

**Comment by Talos-Martin** [comment]
Ok
