### ISSUE TITLE
None != NULL ... kinda

### ISSUE THREAD

**Issue by jsr5194** [Talos-Martin/LearnTheHardWay#9]
https://github.com/Talos-Martin/LearnTheHardWay/blob/c2dfb6b7230488d573a2c93afc5ca345fd1ff15e/Python3/exercise42/ex42.py#L26

You are correct that `None` is a reserved word in python. I just want to clarify that while `None` is used to indicate the absence of something like `NULL` in C, a comparison of the two would not result in true. `None` is a special type in python intended to fill the same purpose though. 

```
None
The sole value of the type NoneType. None is frequently used to represent the absence of a value, as when default arguments are not passed to a function. Assignments to None are illegal and raise a SyntaxError.

ref: https://docs.python.org/3/library/constants.html
```

**Comment by Talos-Martin** [comment]
Got it
